### ISSUE TITLE
Is info in maintainers file current?

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/costreport#15]
Hi -- seems to be a bit outdated.

**Comment by mawenzel** [comment]
Hi, no it is not. But what is wrong with this repo Lauri ;)

**Comment by LappleApple** [comment]
@mawenzel If someone has a question or issue, they won't know whom to ask. So I'd update the maintainers file.

**Comment by mawenzel** [comment]
I updated the maintainers file

**Comment by LappleApple** [comment]
Thank you, @mawenzel
