### ISSUE TITLE
Could this be useful to non-Zalandos?

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/costreport#16]
Seems like it. If so, we can move it to the main GitHub org and spiffy it up a little README-wise.

**Comment by prayerslayer** [comment]
Well, it needs on at least one undocumented API for teams information, but I think one can circumvent this by providing a custom CSV file. Could possibly work for non-Zalandos, but we do not plan to maintain this for long anymore, so I wouldn't make the effort of moving it to the main org.

**Comment by LappleApple** [comment]
Thanks, @prayerslayer. Just drop me a line when we decide to deprecate, I'll push it off to the Incubator.
